[tool.poetry]
name = "general-corruptions"
version = "0.10.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "general_corruptions"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
pandas = "2.0.3"
numpy = "1.24.3"
pillow = "10.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
