version: '3.9'

services:
  minio: 
    image: quay.io/minio/minio 
    restart: unless-stopped 
    entrypoint: sh 
    command: -c 'mkdir -p /data_minionew/model-repository && minio server /data_minionew --console-address "0.0.0.0:9001"' 
    environment: 
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: password 
    expose: 
      - 9000 
      - 9001 
    ports: 
      - 9001:9001 
      - 9000:9000
    volumes: 
      - ~/data/minio:/data_minionew
    networks:
      - app-network
