[tool.poetry]
name = "fairness-metrics-toolbox-for-classification"
version = "0.10.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "fairness_metrics_toolbox_for_classification"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = "1.24.3"
scikit-learn = "1.4.0"
joblib = "1.3.2"
scipy = "1.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
