apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiverify-shared-pvc
  namespace: aiverify
  labels:
    app.kubernetes.io/name: aiverify-shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
---
